# .travis.yml
 
language: php
 
sudo: false
 
php:
  - 7.0
  - 7.1
 
script:
  - echo 'Tested'

before_deploy:
  - cd library/js
  - npm install
  - cd ../..
  - git submodule init
  - git submodule update
 
deploy:
  - provider: wordpress-plugin
    edge:
      source: TypistTech/dpl
      branch: add-wordpress-plugin-deployment
    on:
      php: 7.1
      tags: true
      repo: assemblee-virtuelle/wp-ldp
    slug: wp-ldp
    username: balessan
    password: $WORDPRESS_ORG_PASSWORD
    build_dir: build 
