# .travis.yml

language: php

sudo: false

php:
  - 7.0
  - 7.1

script: phpunit Test.php

branches:
  only: 
    - master

deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh
    on:
      branch: master
      php: 7.0
